### PR TITLE
Fix some things breaking when "Save individual images" is unticked

### LINKED ISSUE #480: Simple img2text gives division by 0 error
### What happened?

Note: was using the previous version of a couple days ago and it was fine
image

### Version

0.0.1 (Default)

### What browsers are you seeing the problem on?

Chrome

### Where are you running the webui?

Windows

### Custom settings

_No response_

### Relevant log output

```shell
Traceback (most recent call last):
  File "C:\Users\Shadow\.conda\envs\ldm\lib\site-packages\gradio\routes.py", line 247, in run_predict
    output = await app.blocks.process_api(
  File "C:\Users\Shadow\.conda\envs\ldm\lib\site-packages\gradio\blocks.py", line 641, in process_api
    predictions, duration = await self.call_function(fn_index, processed_input)
  File "C:\Users\Shadow\.conda\envs\ldm\lib\site-packages\gradio\blocks.py", line 556, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\Shadow\.conda\envs\ldm\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\Shadow\.conda\envs\ldm\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\Shadow\.conda\envs\ldm\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "scripts/webui.py", line 1053, in txt2img
    output_images, seed, info, stats = process_images(
  File "scripts/webui.py", line 969, in process_images
    grid = image_grid(output_images, batch_size)
  File "scripts/webui.py", line 456, in image_grid
    cols = math.ceil(len(imgs) / rows)
ZeroDivisionError: division by zero
[MemMon] Recording max memory usage...
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by EyeDeck**
Fixes #480 
For some reason, the code that adds an image to output_images—which goes back out to the web UI, and into the function that creates a grid if that's enabled—was conditionalized to _only_ run when `not skip_save`, i.e. when "Save individual images" is ticked.
Not sure if there was some reason for this at some point, or if someone just got the indentation level confused.

### CODE REVIEW

**Comment by EyeDeck** [comment]
It looks like the root of this was the change from a couple days ago: https://github.com/hlky/stable-diffusion-webui/commit/dffdaaaf774081fb782f5c56c32e89f8d1392306
Not sure what the intention was there, seems like `process_images()` is a big mess at this point on account of those post-processors getting kind of shoehorned into the main txt/img2img functions so I'm not surprised. The `output_images.append(image)` line was never conditionalized at all in older versions (e.g. [my old fork](https://github.com/hlky/stable-diffusion/blob/main/scripts/txtimg_k_gradio_mod_v2.py#L308)), let alone buried a few indentations deep.
🤷‍♂️

**Comment by HenkDz** [comment]
Yes noticed this as well.

**Review by jjisnow — COMMENTED** [review]
Should have `output_images.append(image)` run anyway to make image appear in the gallery even if the images are saved to file.

**Comment by EyeDeck** [comment]
If you just did that then you'd end up with duplicate images most of the time. 

I think the only thing that would _turn off_ images showing up in the UI after this PR is if post-processing is turned on, where I assume the intention is to only show the post-processed images.
However this is kind of a non-issue because, as I understand it, all post-processing is getting moved to a separate tab, and being taken out of txt/img2img, because the way it is now has made some super messy code, and nobody really understands or can agree on what it _should_ do when post-processing is turned on. In fact I think that change was _already_ committed, but was almost immediately (partially) reverted by another commit, and...
Man, `process_images()` is such a confusing mess right now.

**Comment by jjisnow** [comment]
Maybe just unindenting Line 944-948 one step would do the trick? It would mean the image gets added to the visual gallery regardless of if it's saved. Atm, this doesn't happen if "save individual images" is not ticked

**Comment by EyeDeck** [comment]
That's exactly what the PR fixes.

**Comment by jjisnow** [comment]
> That's exactly what the PR fixes.

Sorry about that, I misread the diff to mean remove those lines of code. Definitely my bad.

**Comment by hlky** [comment]
@EyeDeck txt2img()/img2img() -> process_images() + func_sample() + func_init is a real mess

**Pull request merged**
