### PR TITLE
fix: minor painterro integration fixes

### PR DESCRIPTION
**Pull request by nderscore**
* Prevent multiple script tags from being loaded if the `Advanced Editor` button is pressed rapidly before painterro has been loaded
* Prevent styles from being applied more than once
* Handle painterro script loading errors more gracefully
  * Remove the script tag after an error occurs to allow re-attempts
  * Log the error event instead of `false`
  * (maybe painterro should be served by the webui directly instead to avoid this scenario and improve the offline experience?)

### CODE REVIEW

**Comment by codedealer** [comment]
Removing an external call to CDN is certainly something I pondered before. Do you have an idea how to serve it locally lazily? I see no benefit just bundling painterro.js along with index.js on load.

**Comment by nderscore** [comment]
> Do you have an idea how to serve it locally lazily?

Not sure how feasible it is, but maybe there's a way to serve these static assets (CSS and JS, including libraries, or maybe even images or fonts in the future) from a folder, more like a webserver?

**Comment by codedealer** [comment]
Not to my knowledge. Serving of static assets is completely blackboxed by Gradio.

The only way I see to do this without bundling it is getting it separately on _js hook of clicking "Advanced Editor" button.

A method similar to [this](https://github.com/hlky/stable-diffusion/blob/fe76828926653f979263b4c9d0bf7acc75f4aad2/frontend/css_and_js.py#L16) that will read it from a separate file `painterro.js` and dump it as a string for eval, followed immediately by the call to `SD.Painterro.init()`

**Comment by hlky** [comment]
These changes are okay I think, everything still works at least.

@altryne this is something we could ask gradio to change 

> Not to my knowledge. Serving of static assets is completely blackboxed by Gradio.
> 
> The only way I see to do this without bundling it is getting it separately on _js hook of clicking "Advanced Editor" button.
> 
> A method similar to [this](https://github.com/hlky/stable-diffusion/blob/fe76828926653f979263b4c9d0bf7acc75f4aad2/frontend/css_and_js.py#L16) that will read it from a separate file `painterro.js` and dump it as a string for eval, followed immediately by the call to `SD.Painterro.init()`

**Comment by codedealer** [comment]
Yep, they allow to pass `css` as a file into Blocks constructor so it should not be out of the question to just allow serve us arbitrary css/js files. Even if they put a limit on one .css and one .js, the files can be bundled during the preprocess and then served as static content like from any other server.

Extendable gradio components is another major want. The ability to change the functionality of something like mask editor would go a long way.

**Comment by altryne** [comment]
@codedealer please consdier adding those requests in Gradio repo! 
I've had an amazing chat with them today and they are really open to feedback. 
Loading a JS file/library was one of my top wants! 
https://github.com/gradio-app/gradio/issues

**Comment by codedealer** [comment]
@altryne I made a general feature request gradio-app/gradio#2137. Feel free to pitch in if you have something to expand upon it.

**Pull request merged**
