### PR TITLE
Fixed ports not opening on 7860

### PR DESCRIPTION
**Pull request by JoshuaKimsey**
Fixed the issue where, after a crash or quick relaunch, SD would not use the same port. It will now wait for 7860 to reopen before launching the webui again.

This is related to issue #413 and does provide a fix for it. It is not the most ideal fix, as it can take upwards of 30 seconds for the port to reopen once again. Ideally, when something like an OOM error is encountered, the port should be closed first to free it up before relaunching. But for now, this provides a fix for the issues that allows people to maintain their set parameters without needing to navigate to a new page one port number upwards.

(Heh, apologies if I did something wrong with regards to formatting or anything. This may well be the first time I've ever contributed Python code to something 😅 )

### CODE REVIEW

**Comment by inukai132** [comment]
You might want to change the print to use the value in `gradio_params['server_port']` instead of hardcoding the port number so people can run it on any port and get proper error messages.

**Comment by JoshuaKimsey** [comment]
@inukai132 Really good suggestion actually. I went ahead and gave users the ability to choose their own port at startup, using the parser argument `--port`, which will also be reflected in the error message for a port not being available.

**Comment by inukai132** [comment]
Nice, I appreciate the port moving to command line. Now I don't have to change it every time I pull, lol

**Comment by hlky** [comment]
I think this must another linux thing @JoshuaKimsey 😉

**Comment by JoshuaKimsey** [comment]
Lol, if it was I'd actually be surprised, it kinda seems like it may be a gradio bug, tbh. It is a bit weird it plugs up that port for 10's of seconds after the program quits. But ultimately this fix is a decent work around for that, until a better solution is found. Plus, it let's people choose their own ports if they wish.

**Pull request merged**
