### PR TITLE
bugfix: on submit prompt event in img2img

### PR DESCRIPTION
**Pull request by codedealer**
Following the discussion in #313 there is indeed a bug in [submit event](https://github.com/hlky/stable-diffusion/blob/2cb47b6a2ca64c08d1e0b6734a234cc57f37b23c/frontend/frontend.py#L290). It only assumes that the img2img is in Crop mode so it fails in Mask mode.

The way to fix this would be to check which mode is on but **there  is already another mode button in there** so instead I opted out to a simple js fix.

The code finds the first active generate button and clicks it just like a human would. Nice and easy.

### CODE REVIEW

**Comment by codedealer** [comment]
@hlky also regarding the concerns about excessive buttons in #327 I agree. This bug shows that this interface is slowly becoming unmaintainable with multiple modes piling on in a single file that have side effects like hiding buttons.

Unironically the only good additional option is Painterro because it's atomic and only acts on img2img editor by taking data from it and returning it when closed.

**Comment by jansteffen** [comment]
I definitely feel like this project is already hitting the limits of gradio, it's quite apparant that it was just designed to be able to very quickly whip together a basic but functional UI, but doesn't have nearly the flexability to support a "well designed" UI for a larger project.

With the absolute gold rush of ideas that have emerged since the release of SD the scope of this project has grown every single day, and I don't think it's maintainable.

**Comment by nderscore** [comment]
> This bug shows that this interface is slowly becoming unmaintainable with multiple modes piling on in a single file that have side effects like hiding buttons.

I think the biggest problem this project is suffering from right now is that it's rubbing up against the limitations of gradio, and instead of working with it, there are a lot of non-gradio hacks slapped on top of it, which may or may not work in all scenarios and are really hard to debug and maintain. 

I would like to see the code try to work within gradio's limitations more, like the updated painterro integration.

**Comment by codedealer** [comment]
Gradio brings a lot to the table in terms of visualization and the ease of interfacing from the machine learning side. Rebuilding this in something else can be very time consuming although I saw some nice the examples of non-gradio UIs on SD discord.

**Comment by hlky** [comment]
@altryne has been talking to the people over at Gradio and they will be making some changes to accommodate what we're trying to do

This fixes the bug people were having though, thanks

Regarding UI complexity/messiness this will be looked at soon

**Pull request merged**
