### PR TITLE
Refactored the UI into it's own module

### LINKED ISSUE #197: [SUGGESTION] - Break the python code apart
If we extract the "ui" part out of the webui.py script, and then use it with an import, then we can do a few things : 

1) Develop UI faster - this would be possible as we could import the Gradio UI into a separate python file and run with debug=True (that's actually how I've been doing the dev, but it takes a long time to copy/paste back and forth) 

2) Write stubs for all functions we use to load the ui dev faster

3) Merge syncs and PR reviews will be easier

### PR DESCRIPTION
**Pull request by altryne**
fixes #197 and adds the following:
`webui_playground.py` file can be run with `gradio webui_playground.py` and will not load any models, run on mac etc' 
new module called frontend @hlky your sync script will prob. need attention? I think you're syncing just a few named files right now? 

Fixed as much JS as I could, and fixed all the pushy buttons, they all push where they need to. 
Refactored the UI a bit in the img2img tab, but it still needs work

### CODE REVIEW

**Comment by altryne** [comment]
I haven't had time to check this in the actual repo, as this is now more involved, please help test if you can before merge

**Comment by hlky** [comment]
Check sync.yml see if the frontend is going to the right place, I assume you wanted it to be synced to scripts/frontend
If not let me know
Although if playground is intended only for development I'll keep it only on the dev repo

**Comment by hlky** [comment]
Ah, it's expecting it in main folder

**Comment by altryne** [comment]
Yeah I don't believe it needs to be in the main repo as it's only for fast dev

**Comment by hlky** [comment]
```
File "s:\ai\hlky\stable-diffusion\frontend\frontend.py", line 120, in draw_gradio_ui
    value=img2img_defaults['prompt'],
KeyError: 'prompt'
```

**Comment by hlky** [comment]
That's due to the UI defaults thing, probably needs moving over or something, or removing if it's too much hassle, I doubt anyone is using it

**Comment by hlky** [comment]
```
File "scripts/webui.py", line 1434, in <module>
    demo = draw_gradio_ui(opt, txt2img_defaults=txt2img_defaults)
  File "s:\ai\hlky\stable-diffusion\frontend\frontend.py", line 174, in draw_gradio_ui
    value=img2img_defaults['batch_size'])
```

**Comment by jansteffen** [comment]
Hmm what's strange about that is that both the keys `prompt` and `batch_size` are defined in webui.py at line 1308. Maybe something is going wrong in line 1325: `txt2img_defaults.update(user_defaults['txt2img'])`

But uhh, look guys I gotta be honest, I just moved some UI elements around lol, I'm kinda out of my depth here lmao

**Comment by altryne** [comment]
ugh, this is what I get for not testing on the actual use with models, 
Taking a look

@hlky this is all you get as an error?

**Comment by altryne** [comment]
>I doubt anyone is using it
I think if we save it when they change, it'll be super useful? I meant to, as I often want specific settings and am tired of them resetting hehe

**Comment by hlky** [comment]
@altryne  yes but also 

`
No ImageEditor...
`

```
Loaded GFPGAN
Loaded RealESRGAN with model RealESRGAN_x4plus
Loading model from models/ldm/stable-diffusion-v1/model.ckpt
Global Step: 470000
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
No ImageEditor...
Running on local URL:  http://localhost:7860/

To create a public link, set `share=True` in `launch()`.
```

**Comment by altryne** [comment]
did you merge the ImageEditor thingie?

**Comment by altryne** [comment]
@hlky the errors above the imageEditor were fixed I believe, can you please try again? 🙏

**Comment by hlky** [comment]
Oh it needs that as well? 

Do you want to both pr your changes to [ui-overhaul](https://github.com/hlky/stable-diffusion-webui/tree/ui-overhaul) branch?  @altryne @jansteffen 
I can't figure out how to move these 2 pr to the new branch i made 😕

**Comment by altryne** [comment]
>Oh it needs that as well? 
No it doesnt, I think maybe you had both codes somehow locally? 
CleanShot 2022-08-28 at 17 25 52@2x

I have no mentiones of ImageEditor in my repo / code base

**Comment by hlky** [comment]
idk, ui loads now anyway but

when using img2img

```
Traceback (most recent call last):
  File "C:\Users\user\.conda\envs\ldm-waifu5\lib\site-packages\gradio\routes.py", line 247, in run_predict
    output = await app.blocks.process_api(
  File "C:\Users\user\.conda\envs\ldm-waifu5\lib\site-packages\gradio\blocks.py", line 641, in process_api
    predictions, duration = await self.call_function(fn_index, processed_input)
  File "C:\Users\user\.conda\envs\ldm-waifu5\lib\site-packages\gradio\blocks.py", line 556, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\user\.conda\envs\ldm-waifu5\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\user\.conda\envs\ldm-waifu5\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\user\.conda\envs\ldm-waifu5\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "scripts/webui.py", line 1168, in img2img
    output_images, seed, info, stats = process_images(
  File "scripts/webui.py", line 694, in process_images
    init_data = func_init()
  File "scripts/webui.py", line 1061, in init
    image = resize_image(resize_mode, image, width, height)
NameError: name 'resize_image' is not defined
```

**Comment by hlky** [comment]
txt2img is working

**Comment by altryne** [comment]
ok this looks like something, what did you click?

**Comment by hlky** [comment]
> I have no mentiones of ImageEditor in my repo / code base 

I think I had #201 checked out first time

**Comment by altryne** [comment]
@hlky ugh refactoring is ... 😮‍💨  but the resize_image should be fixed,

**Review by hlky — COMMENTED** [review]
Seems good to me, txt2img and img2img still work
Just need to fix sync.yml hang on

**Comment by jansteffen** [comment]
uuhhh is img2img supposed to look like this? on firefox
image

**Review by hlky — APPROVED** [review]

**Comment by hlky** [comment]
Web capture_29-8-2022_03654_127 0 0 1

Looks like this for me

**Comment by altryne** [comment]
@jansteffen I did move things around, it's not the best, but there was way more scrolling there before

**Comment by jansteffen** [comment]
Hmm ok, well as long as all the functionality is working as expected I guess we can merge this now and I'll see if I can improve the layout a bit tomorrow, it's getting real late for me

**Review by jansteffen — APPROVED** [review]

**Comment by altryne** [comment]
@hlky I think it makes sense that you're the only merger for now? wdyt?

**Comment by hlky** [comment]
I think it's fine for now, merged, can work on any conflicts with #201 now

**Pull request merged**
