### PR TITLE
Variations

### PR DESCRIPTION
**Pull request by xraxra**
I ported the variation code over, 

**example workflow** 
Generate some images, 
grid-00020-4011111491_Usagi_bunny_rabbit,_lain_iwakura,_rei_ayanami_plug_suit,_female_anime_character,_3d_render_beeple,_realistic_detailed_painting,_

Pick one and get the seed (this is a manual step, would be nice to just click the image to populate the seed)
**Seed: 4011111492**

In advanced tab, scale up **Variation Amount** slider, the larger the value the more change (keep Variant Seed empty), 
**Variation Amount: 0.1**
click generate
grid-00021-4011111492_Usagi_bunny_rabbit,_lain_iwakura,_rei_ayanami_plug_suit,_female_anime_character,_3d_render_beeple,_realistic_detailed_painting,_

Now you have variations on a seed...  keep clicking generate to get more variations

If you want to mix between 2 seeds, set the **Variant Seed** and use the **Variation Amount** slider as a mixer between 2 seeds

**Recalling past variants**
This is where it is a little tricky, since Variants are made by 2 sets of noise, one generated from Seed and the other from Variant Seed.. there is no way to have a "unified seed" 
So to recall a variant you need: 

1. Original Image Seed (from filename)
2. Variant Image Seed (from variant filename)
3. Same Variation Amount (as it is acting as a blend between the 2 sets of noise)

### CODE REVIEW

**Comment by hlky** [comment]
image

GitHub pls.. how is this a conflict 😆

**Comment by LiJT** [comment]
Thank you so much!!!!!!

**Comment by hlky** [comment]
@LiJT have you tested it? i haven't got round to it yet, if some other people say it works then ill just merge

**Comment by hlky** [comment]
This is working for me. I used the k_lms settings from the [Benchmarking](https://github.com/hlky/stable-diffusion/wiki/Benchmarking) page and set variation to 0.3 

The original :
00373-50_k_lms_559845130_anime_girl_holding_a_giant_NVIDIA_Tesla_A100_GPU_graphics_card,_Anime_Blu-Ray_boxart,_super_high_detail

-----


6 samples with variation 0.3:
grid-00132-559845130_anime_girl_holding_a_giant_NVIDIA_Tesla_A100_GPU_graphics_card,_Anime_Blu-Ray_boxart,_super_high_detail

**Comment by hlky** [comment]
Good work @xraxra thank you!

**Comment by LiJT** [comment]
> This is working for me. I used the k_lms settings from the [Benchmarking](https://github.com/hlky/stable-diffusion/wiki/Benchmarking) page and set variation to 0.3
> 
> The original : 00373-50_k_lms_559845130_anime_girl_holding_a_giant_NVIDIA_Tesla_A100_GPU_graphics_card,_Anime_Blu-Ray_boxart,_super_high_detail
> 
> 6 samples with variation 0.3: grid-00132-559845130_anime_girl_holding_a_giant_NVIDIA_Tesla_A100_GPU_graphics_card,_Anime_Blu-Ray_boxart,_super_high_detail

Hello Dev!!

How did you make this to work? Currently webui doesnt show Variation option yet

**Comment by altryne** [comment]
Oh this is so awesome!

**Comment by JoshuaKimsey** [comment]
OMG, this is amazing! IT's like the Variations feature from Midjourney. Awesome work, y'all!

**Pull request merged**
