### PR TITLE
Aspect ratio display as a fraction

### PR DESCRIPTION
**Pull request by sbritorodr**
Removed the weird decimal point output and replaced it to a typical aspect ratio fraction (16:9 instead of 1.777)

Note: I've tried to modify lines 38 and 212 from the file [`frontend.py`](https://github.com/hlky/stable-diffusion-webui/blob/320ea01d113096e5d99715b3adbe6b82eb9c0059/frontend/frontend.py) removing these strings:

Line 38 of [`frontend.py`](https://github.com/hlky/stable-diffusion-webui/blob/320ea01d113096e5d99715b3adbe6b82eb9c0059/frontend/frontend.py)
```python
#img2img_dimensions_info_text_box = gr.Textbox(label="Aspect ratio (4:3 = 1.333 | 16:9 = 1.777 | 21:9 = 2.333)")
img2img_dimensions_info_text_box = gr.Textbox(label="Aspect ratio")
```
Line 212 of [`frontend.py`](https://github.com/hlky/stable-diffusion-webui/blob/320ea01d113096e5d99715b3adbe6b82eb9c0059/frontend/frontend.py)
```python
#txt2img_dimensions_info_text_box = gr.Textbox(label="Aspect ratio (4:3 = 1.333 | 16:9 = 1.777 | 21:9 = 2.333)")
txt2img_dimensions_info_text_box = gr.Textbox(label="Aspect ratio")
```
 but at compile time gives me a weird error: 
```
Traceback (most recent call last):
  File "/content/stable-diffusion/scripts/webui.py", line 3, in <module>
    from frontend.frontend import draw_gradio_ui
  File "/content/stable-diffusion/frontend/frontend.py", line 2, in <module>
    from frontend.css_and_js import css, js, call_JS, js_parse_prompt, js_copy_txt2img_output
ImportError: cannot import name 'call_JS' from 'frontend.css_and_js' (/content/stable-diffusion/frontend/css_and_js.py)
```
Note: I'm running it using the [Welcome to Stable Diffusion WebUI - altryne](https://colab.research.google.com/github/altryne/sd-webui-colab/blob/main/Stable_Diffusion_WebUi_Altryne.ipynb). Works nice and only crashes after modifying [`frontend.py`](https://github.com/hlky/stable-diffusion-webui/blob/320ea01d113096e5d99715b3adbe6b82eb9c0059/frontend/frontend.py).

I'm attaching my frontend.py edited. It's weird because it crashes just by modifying a python string.
[frontend-edited.py.txt](https://github.com/hlky/stable-diffusion-webui/files/9477926/frontend.py.txt)

### CODE REVIEW

**Comment by sbritorodr** [comment]
Recently checked out that the colab uses the pin-for colab branch, so that's why it's giving this error (because the main branch doesn't run)

**Comment by JuanLagu** [comment]
Hi @sbritorodr. I created the original aspect ratio calculation. I used the decimal point output because for me it's more useful than a fraction in some cases. Let me share an example:
Imagine I want a 16:9 image, but because we only get multiples of 64 for the dimentions, I can't get exactly a 16:9 resolution.
With the decimal I know a 16:9 resolution would be = 1.777 (as the cheatsheet in the label said), so I could adjust my dimentions until I get as close to 1.777 as I could be. This would be easy to do, and in this particular example the closest number could be 1.75
image

Now let's try with the fractions method. If I select the same dimentions I would get 7:4, and honestly it's not clear at all in my mind what 7:4 would look like. With the decimal system, at least I know I'm close to the desired aspect ratio.
image
Do you really think the fraction method is more useful? Maybe we can have both. For exaple the text could be something like:
"Aspect ratio: 7:4 (1.75)" or something like that. I hope you understand my concern.

**Comment by JuanLagu** [comment]
@sbritorodr  Oh, I also forgot to mention the feature was commented in the code. I can see it was disabled by this user [https://github.com/hlky/stable-diffusion-webui/pull/421](https://github.com/hlky/stable-diffusion-webui/pull/421), and I can see on his pull request "_TODOS - post merge: Restore the aspect ratio calculation_", so maybe there was a problem. I haven't checked it.

**Comment by sbritorodr** [comment]
Hi @JuanLagu
I've understand your point and you've convinced me for using decimal points instead of fractions. I've forgot the height and width are at multiples of 8, hence the weird asoect ratios.

I hope you understand I'm doing this with good faith.

That being said, I'm going to close the PR

Thanks for the review!

**Comment by JuanLagu** [comment]
Sure, no worries @sbritorodr !
I just wanted to bring it up. Thanks for your time anyways! 🙏

**Pull request closed without merging**
