### PR TITLE
feat: simplify prompt weight splitting function

### PR DESCRIPTION
**Pull request by nderscore**
* Replaced almost all of the code in `split_weighted_subprompts` with a single regular expression
* Moved weight normalization code into the function as an argument
* Functionally, it is almost exactly the same as before. I think the regex pattern is a little better at parsing weights in some edge-case scenarios.

With the regex, all of these formats should either still remaining working, or now work:
* `foo:2` integers
* `foo:-1.23` decimals and negative numbers
* `foo:` no weight (defaults to `1`)
* `foo::123` midjourney-style double-colon syntax (it honestly might be nice to enforce this syntax instead, to enable `:` as a character in prompt tokens? :zipper_mouth_face: )
* `foo:2bar:1` `foo:bar` missing space characters between subprompts? no problem
* `foo:2 bar:1` spaces are fine too though
* <code>foo:&nbsp;&nbsp;&nbsp;&nbsp;bar</code> <code>foo:1.2&nbsp;&nbsp;&nbsp;&nbsp;bar:3</code> multiple spaces as well
* `foo:2 bar` and the last subprompt doesn't need a colon
* `foo` and a plain prompt works still too

### CODE REVIEW

**Comment by hlky** [comment]
This is for weighted prompts:1 like:2 this:3 ?

I'll test now, thanks

**Comment by hlky** [comment]
```
  File "scripts/webui.py", line 784
    for i in range(0,len(weighted_subprompts))
```

**Comment by nderscore** [comment]
That's what I get for copy-pasting code between the two repositories, then adjusting some of the variable names :facepalm: Fixed.

**Comment by nderscore** [comment]
With the regex, all of these formats should now work:
`foo` no colon
`foo:2` integers
`foo:-1.23` decimals and negative numbers
`foo::123` midjourney-style double-colon syntax
`foo:2bar:1` missing space between weighted prompts? no problem
`foo:2 bar:1` spaces are fine too though
`foo:2 bar` and the last subprompt doesn't need a colon
```

**Comment by hlky** [comment]
Sorry for the delay @nderscore, these changes are good from my tests.

**Pull request merged**
