### PR TITLE
feat(): replace gr.Image with gr.ImageEditor

### PR DESCRIPTION
**Pull request by oldfndm**
Replaces the image editor with a custom component with a more fully featured editor. 

image

Depends on https://github.com/oldfndm/gradio (based on the 3.1.6 release that the main repo uses)
After installing locally I think https://github.com/oldfndm/gradio/blob/main/CONTRIBUTING.md#install-gradio-locally-from-the-main-branch needs to be run

I left the UI mostly alone to avoid breaking people changing it but the editor should probably be bigger.

### CODE REVIEW

**Comment by hlky** [comment]
Should be able to modify the environment.yaml with `-e git+https://github.com/oldfndm/gradio#egg=gradio` to install gradio from your fork

What do you think about making the Advanced editor a standalone tab that can send an image to the img2img Image component? @altryne could probably make that work and @nderscore made a fix to the js involved so probably understands it too.

That way the img2img tab itself could be simplified to just be for uploading an init image and any masking or cropping, if needed, can be done in a larger area

**Comment by oldfndm** [comment]
> That way the img2img tab itself could be simplified to just be for uploading an init image and any masking or cropping, if needed, can be done in a larger area

Sounds like a good idea, I'll move it to a new tab.

**Comment by altryne** [comment]
@oldfndm this is great, is this your fork of Gradio? 
@hlky I wonder if splitting away from the main branch of Gradio would make this too dependent on this specific usecase, and when Gradio releases new features (they promised to focus on streaming image generation results for example) then we won't be able to enjoy their new feautres (until a merge by @oldfndm )

**Comment by oldfndm** [comment]
Let me know what you decide to avoid fixing the pr if it's not going to get merged.

**Comment by hlky** [comment]
If @oldfndm can merge any new Gradio features when they become available I see no reason to not use the fork

Of course it will involve another environment.yaml change but thanks to the conda update line in webui.cmd this won't be an issue, except for edge cases that blindly update the webui from the dev repo 😆 

The main repo has a dockerfile now too, but I think that's set up to pull changes, so shouldn't be any problem there

**Comment by altryne** [comment]
Reasons to be careful (not to dump on @oldfndm great work!) 

- All components in gradio are unit tested and stable in pip so if we pin the version, we know 100% how it behaves.
- If we add a pip dependency from github master branch, it removes quality control from this repo, and can behave unexpectedly for users that will not understand what's going on, and likely open a ticket here. 
- The above fork of gradio has fixes as late as two hours ago, it feels like it's still in dev and doesn't feel stable
- Considering the Colab fork (and hopefully a future notebook we'll add to the main branch) this can be even worse, as packages get installed every time you re-run colab

**Comment by hlky** [comment]
> Colab fork

Yes there are a few colabs using this repo

> hopefully a future notebook we'll add to the main branch

An official colab would be a good feature

**Comment by jansteffen** [comment]
> Reasons to be careful (not to dump on @oldfndm great work!)
> 
>     * All components in gradio are unit tested and stable in pip so if we pin the version, we know 100% how it behaves.
> 
>     * If we add a pip dependency from github master branch, it removes quality control from this repo, and can behave unexpectedly for users that will not understand what's going on, and likely open a ticket here.
> 
>     * The above fork of gradio has fixes as late as two hours ago, it feels like it's still in dev and doesn't feel stable
> 
>     * Considering the Colab fork (and hopefully a future notebook we'll add to the main branch) this can be even worse, as packages get installed every time you re-run colab

I agree with these, and I also think there's value in simplicity, both for maintainance and ease of use. The scope of this project has ballooned massively in just one week already.

Also there are already other people working on stable diffusion integrations for photoshop and gimp. For what this project is trying to do, the basic crop and mask mode are sufficent imo

**Comment by oldfndm** [comment]
Just updated the PR to move everything into its own tab.

**Comment by hlky** [comment]
@oldfndm ready to merge?

**Comment by gmq** [comment]
Give me a second, I'm fixing how the masks works

**Comment by oldfndm** [comment]
Give me a second, I'm fixing the masks.

**Comment by altryne** [comment]
@oldfndm sorry to do this to you 😓 
Mind taking a look at #229 ? 
I refactored the UI out to it's own layer, should be easier to work (for example the UI can be run on a mac, have auto reload etc') 

Can you wait / rebase your work on top of that one?

**Comment by altryne** [comment]
@hlky how about merging this into a branch so we can play around with it and see if it makes sense? or since there are 2 repos, this is problematic?

**Comment by gmq** [comment]
@hlky it's done

@altryne I'm sorry, I don't have the energy to do another rebase

**Comment by oldfndm** [comment]
@hlky it's done

@altryne I'm sorry, I don't have the energy to do another rebase

**Comment by altryne** [comment]
CleanShot 2022-08-28 at 17 05 15@2x
What's going on?

**Comment by hlky** [comment]
Probably alt account lol

**Comment by hlky** [comment]
> @hlky how about merging this into a branch so we can play around with it and see if it makes sense? or since there are 2 repos, this is problematic?


Is there an easy way to do this? can't see the option from this page

**Comment by altryne** [comment]
CleanShot 2022-08-28 at 17 07 17@2x
I think as an owner you can change the base of the PR branch here, I can't as collaborator

**Comment by altryne** [comment]
@hlky edited this PR into the `ui-overhaul` branch

**Comment by hlky** [comment]
No direct conflicts
image

Needs testing first though I guess

**Comment by hlky** [comment]
image

Just an (almost) empty tab for me

**Comment by oldfndm** [comment]
Yeah, it needs the gradio fork to display the rest of the tab but at least it won't break if it's not installed.

**Comment by hlky** [comment]
@oldfndm oh right, forgot about that, i'll leave it for right now then because it will only make issues be created about it being blank, it's nearly 1am here, past few days I've stayed up until like 6am working on this, I think I'll get an earlier night tonight and sort out the environment.yaml changes in the morning

**Comment by altryne** [comment]
get some rest @hlky \

**Comment by pngwn** [comment]
Hey folks. I'm on the Gradio teams and just wanted to give some info on what we are up to with the Sketch tool.

We are currently working on improving the Image component's sketch mode to include adjustable brush sizes + colours, so simple sketching will be possible as well as simple (the sketch tool already supports adding background images to Sketch or Mask over). There will be no fill or polygon tool in this iteration (which should come within a week or two, although no promises) but they may come in the future.

Hopefully this information is helpful while you're deciding how to proceed with this PR (which is very cool btw!)

**Comment by oldfndm** [comment]
I'm going to close this PR, going with the official version once the sketch tool has been improved sounds like a much better idea for this repo, to avoid issues in the future.

**Comment by hlky** [comment]
@pngwn this will be great, thank you!

@oldfndm agreed, no environment.yaml change needed now

**Comment by altryne** [comment]
@oldfndm thanks for your work! ❤️

@pngwn could be cool to have basic masking features but maybe also basic drawing features? 
Something like this with a few lines could be really cool 
image
As implemented here (not with Gradio) :
https://huggingface.co/spaces/huggingface/diffuse-the-rest

**Comment by pngwn** [comment]
@altryne Yeah, that should be pretty much reproducible with Gradio when these changes are in (iterative output is also being worked on but may take a little longer). The 'drawing' tools will be in addition to the masking tools.

**Pull request closed without merging**
