### PR TITLE
added gobig configuration sliders

### PR DESCRIPTION
**Pull request by devilismyfriend**
steps and strength for txt2img and gobig tab

### CODE REVIEW

**Review by hlky — CHANGES_REQUESTED** [review]
resolve conflicts please, updating your branch from master should fix i think

**Comment by devilismyfriend** [comment]
done

**Comment by HenkDz** [comment]
> done

Now it's throwing memory errors. Seems like it needs more VRAM now.

**Comment by HenkDz** [comment]
And this error now shows regardless of the settings bellow. I have unchecked goBIG and still get it.

image

**Comment by devilismyfriend** [comment]
> > done
> 
> Now it's throwing memory errors. Seems like it needs more VRAM now.

it will need more ram if you're trying to upscale something larger then the normal outputs at 512x512

**Pull request merged**
