### PR TITLE
fixed goBig img2img

### PR DESCRIPTION
**Pull request by devilismyfriend**
fixed _ in sampler causing an error
fixed the missing variables under the else statement of img2img

tested working

### CODE REVIEW

**Comment by devilismyfriend** [comment]
```
samples_ddim, _ = K.sampling.__dict__[f'sample_{sampler.get_sampler_name()}'](model_wrap_cfg, xi, sigma_sched, extra_args={'cond': conditioning, 'uncond': unconditional_conditioning, 'cond_scale': cfg_scale}, disable=False)
ValueError: not enough values to unpack (expected 2, got 1)
```

error in question, this happens even with the current branch without gobig so I'm not sure where it was introduced, removing the additional _ fixes it

**Comment by hlky** [comment]
Going to leave this for now, there are plans to add other upscalers, so this can be added at the same time

Also, it's currently open to discussion whether all these different upscalers should be only usable on their respective standalone tabs, if you think about it there isn't any reason to have the options on generation, not every generation of a batch will need gfpgan for example, not every image will be good enough to warrant upscaling, these things are essentially post-processing and should probably be changed to be implemented only as post-processing, perhaps with an "undocumented" cli flag to enable them, for people who absolutely know what they are doing

**Comment by devilismyfriend** [comment]
Yeah I can see what you mean, on the generator itself it's mainly used for people wanting to automate stuff

**Comment by devilismyfriend** [comment]
Do keep in mind that img2img is completely unusable right now because of the error I mentioned, regardless of gobig, only DDIM works.

**Comment by hlky** [comment]
> Do keep in mind that img2img is completely unusable right now because of the error I mentioned, regardless of gobig, only DDIM works.

That should be fixed 7518c3a

**Comment by hlky** [comment]
https://github.com/hlky/stable-diffusion-webui/wiki/Upscalers

**Comment by ooofest** [comment]
> > Do keep in mind that img2img is completely unusable right now because of the error I mentioned, regardless of gobig, only DDIM works.
> 
> That should be fixed [7518c3a](https://github.com/hlky/stable-diffusion-webui/commit/7518c3ac27e7a85c9b63452917a9ebe72487e376)

I can confirm this fixed the same symptoms I was experiencing as those mentioned in https://github.com/hlky/stable-diffusion-webui/pull/170#issuecomment-1229356874

**Comment by hdon1** [comment]
As of playing with it yesterday, the gobig image outputs were being overwritten each run. I looked into the code and saw that the gradio interface for image uploading doesn't seem to carry the original filename at all. Perhaps the simple solution is to just check the gobig output folder and sequentially number successive upscaling run ouputs.

**Comment by hdon1** [comment]
The gradio interface to retrieve uploaded images doesn't carry filename along, so to prevent the gobig image output from being overwritten after each run we might check the folder and just sequentially number the outputs

**Comment by devilismyfriend** [comment]
> The gradio interface to retrieve uploaded images doesn't carry filename along, so to prevent the gobig image output from being overwritten after each run we might check the folder and just sequentially number the outputs

yeah that's a known thing, when using the gobig tab the image created gets a random name of "image_xxxxxxx", x being a number

**Comment by Oceanswave** [comment]
@devilismyfriend love the work and the GoBig results - could you possibly update this to fall in neatly with the rest of the UI changes being pulled into a separate file?

**Pull request closed without merging**
