### PR TITLE
webui: alphabetize arguments

### PR DESCRIPTION
**Pull request by mchaker**
code cleanup/nit

makes it easier to find args

### CODE REVIEW

**Comment by hlky** [comment]
> alphabetize arguments

Sure, why not

**Comment by JoshuaKimsey** [comment]
Uhh @hlky I think this just overwrote the `--port` argument I implemented in the PR before this one.

**Comment by mchaker** [comment]
> Uhh @hlky I think this just overwrote the `--port` argument I implemented in the PR before this one.
> 
> I don't see it in the main webui.py file either.

Yeah I just made a fix for that oops sorry :(

**Comment by JoshuaKimsey** [comment]
Lol, no worries. It's actually nice to see them alphabetized, I was sorta guessing where to place the port one when I did it, so this makes it a lot easier.

**Pull request merged**
