### PR TITLE
fix img2img mask generation

### PR DESCRIPTION
**Pull request by codedealer**
Quick fix to get mask generation back to work. Added mask editor as a separate argument so people stop forgetting it exists.

Closes: #587, Closes: #565, Closes: #564, Closes: #559

### CODE REVIEW

**Comment by yacineMTB** [comment]
damn you beat me to it :P

**Comment by codedealer** [comment]
@yacineMTB well it's good to confirm the solution!

**Comment by WolfShadowheart** [comment]
Thanks, I've been having this issue as well. 

My apologies as I'm not very familiar with git, do I simply git clone https://github.com/hlky/stable-diffusion-webui.git and reapply, or is there something else that I'm supposed to do?

Thanks!

**Comment by yacineMTB** [comment]
@hlky heads up, I think this breaks *other* img2img modes
:eyes:

**Pull request merged**
