### PR TITLE
Batch and row support for simple templating

### PR DESCRIPTION
**Pull request by JustOxlamon**
- Simple templating now support batches
For prompt `@(big|small) city lights` and seed 1 it will be create 4 images:

`big city lights` seed = 1,2
`small city lights` seed = 1,2

- Grid image rows = first group variant count

### CODE REVIEW

**Comment by hlky** [comment]
Is this not already implemented?

https://github.com/hlky/stable-diffusion-webui#prompt-combinations

**Comment by nahojjjen** [comment]
Templates work, but batches+templates didn't last I tested.
So even if you set it to generate 4 batches, it just makes 1.

For example, if you input this prompt:
"@(green | red) (ball)"
with 4 batches
it should generate 8 images, 
4 "green ball"
4 "red ball"

instead it only generates 2 images
1 "green ball"
1 "red ball"

**Comment by JustOxlamon** [comment]
I think it is reverted somehow last time. So i do it again.

**Review by hlky — APPROVED** [review]

**Comment by hlky** [comment]
@JustOxlamon just realised it was your feature to begin with, thanks for the fix

**Pull request merged**
