### PR TITLE
Job Manager feature - view images before all are complete, cancel ongoing generations

### PR DESCRIPTION
**Pull request by cobryan05**
Adds a "Job Manager" which wraps txt2img and img2img to provide the ability to view images as they are generated, and to cancel long-running jobs.

img2img UI is broken on my machine even without my changes, so I haven't been able to verify that part of it.

Adds a 'Job Manager' tab under 'Number of images to generate':

image

The 'Stop' button stops the current generation (after the current batch completes) and returns the results.
The 'Refresh' button fills the gallery with the currently generated images.

This tricks Gradio into allowing this by using several hidden gr.Components which decouples the 'Generate' button from the gallery, allowing the gallery to be written to while generation is occuring.

### CODE REVIEW

**Comment by hlky** [comment]
@cobryan05 hey I was working on img2img support for this and got it working somewhat, but it regressed behavior that was fixed a few days ago and the actual job info did not display, so you might want to revert those changes, and rebase off the current master, then hopefully img2img will work and you'll be able to see why the job info isn't displaying
Very good work though, functions fine on txt2img, thank you

**Comment by cobryan05** [comment]
Looks like I mixed up an img2img input parameter, and forgot to pass job_info along in webui.py img2img function. It seems to work now

**Comment by Nyxeka** [comment]
Doesn't seem to support having multiple tabs queueing up several requests (having multiple clients queueing requests) which is usually built into gradio

**Comment by cobryan05** [comment]
> Doesn't seem to support having multiple tabs queueing up several requests (having multiple clients queueing requests) which is usually built into gradio

Yes, this does not currently support queueing (see [this commit message](https://github.com/hlky/stable-diffusion-webui/pull/460/commits/a586aa6d88a866573c5be9bef1c971e692c0913f) ).

That'd definitely be a 'nice to have' for me. Maybe I or someone else will add it. For now you can easily disable this feature and get the old queueing behavior with the --no-job-manager parameter.

**Comment by cobryan05** [comment]
> Doesn't seem to support having multiple tabs queueing up several requests (having multiple clients queueing requests) which is usually built into gradio

*mutter* Didn't want to work on queueing tonight but it got stuck in my head.
Take your queueing. But the UI doesn't do a terrific job of telling you that's happening.

**Pull request merged**
